INSERT INTO airlines (id, name, country) VALUES ('0A', 'Amber Air', 'LT');
INSERT INTO airlines (id, name, country) VALUES ('0B', 'Blue Air', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('0C', 'IBL Aviation', 'MU');
INSERT INTO airlines (id, name, country) VALUES ('0D', 'Darwin Airline', 'CH');
INSERT INTO airlines (id, name, country) VALUES ('0J', 'Jetclub', 'CH');
INSERT INTO airlines (id, name, country) VALUES ('A2', 'Cielos Airlines', 'PE');
INSERT INTO airlines (id, name, country) VALUES ('A3', 'Aegean Airlines', 'GR');
INSERT INTO airlines (id, name, country) VALUES ('A4', 'Southern Winds Airlines', 'AR');
INSERT INTO airlines (id, name, country) VALUES ('A5', 'Airlinair', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('A6', 'Air Alps Aviation', 'AT');
INSERT INTO airlines (id, name, country) VALUES ('A7', 'Air Plus Comet', 'ES');
INSERT INTO airlines (id, name, country) VALUES ('A8', 'Benin Golf Air', 'BJ');
INSERT INTO airlines (id, name, country) VALUES ('A9', 'Georgian Airways', 'GE');
INSERT INTO airlines (id, name, country) VALUES ('AA', 'American Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('AB', 'Air Berlin', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('AC', 'Air Canada', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('AD', 'Air Paradise International', 'ID');
INSERT INTO airlines (id, name, country) VALUES ('AE', 'Mandarin Airlines', 'TW');
INSERT INTO airlines (id, name, country) VALUES ('AF', 'Air France', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('AG', 'Air Contractors', 'IE');
INSERT INTO airlines (id, name, country) VALUES ('AH', 'Air Algérie', 'DZ');
INSERT INTO airlines (id, name, country) VALUES ('AI', 'Air India Limited', 'IN');
INSERT INTO airlines (id, name, country) VALUES ('AJ', 'Aero Contractors', 'NG');
INSERT INTO airlines (id, name, country) VALUES ('AK', 'AirAsia', 'MY');
INSERT INTO airlines (id, name, country) VALUES ('AL', 'Transaviaexport', 'BY');
INSERT INTO airlines (id, name, country) VALUES ('AM', 'Aeroméxico', 'MX');
INSERT INTO airlines (id, name, country) VALUES ('AN', 'Ansett Australia', 'AU');
INSERT INTO airlines (id, name, country) VALUES ('AO', 'Australian Airlines', 'AU');
INSERT INTO airlines (id, name, country) VALUES ('AP', 'Air One', 'IT');
INSERT INTO airlines (id, name, country) VALUES ('AQ', 'Aloha Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('AR', 'Aerolineas Argentinas', 'AR');
INSERT INTO airlines (id, name, country) VALUES ('AS', 'Alaska Airlines, Inc.', 'US');
INSERT INTO airlines (id, name, country) VALUES ('AT', 'Royal Air Maroc', 'MA');
INSERT INTO airlines (id, name, country) VALUES ('AU', 'Austral Lineas Aereas', 'AR');
INSERT INTO airlines (id, name, country) VALUES ('AV', 'Avianca - Aerovias Nacionales de Colombia, S.A.', 'CO');
INSERT INTO airlines (id, name, country) VALUES ('AW', 'Dirgantara Air Service', 'ID');
INSERT INTO airlines (id, name, country) VALUES ('AX', 'Trans States Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('AY', 'Finnair', 'FI');
INSERT INTO airlines (id, name, country) VALUES ('AZ', 'Alitalia', 'IT');
INSERT INTO airlines (id, name, country) VALUES ('B2', 'Belavia Belarusian Airlines', 'BY');
INSERT INTO airlines (id, name, country) VALUES ('B3', 'Bellview Airlines', 'NG');
INSERT INTO airlines (id, name, country) VALUES ('B4', 'BACH Flugbetriebsges', 'AT');
INSERT INTO airlines (id, name, country) VALUES ('B5', 'Flightline', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('B6', 'JetBlue Airways', 'US');
INSERT INTO airlines (id, name, country) VALUES ('B8', 'Eritrean Airlines', 'ER');
INSERT INTO airlines (id, name, country) VALUES ('B9', 'Air Bangladesh', 'BD');
INSERT INTO airlines (id, name, country) VALUES ('BA', 'British Airways', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('BB', 'Seaborne Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('BC', 'Skymark Airlines', 'JP');
INSERT INTO airlines (id, name, country) VALUES ('BD', 'BMI', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('BE', 'Flybe', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('BF', 'Bluebird Cargo', 'IS');
INSERT INTO airlines (id, name, country) VALUES ('BG', 'Biman Bangladesh Airlines', 'BD');
INSERT INTO airlines (id, name, country) VALUES ('BH', 'Hawkair', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('BI', 'Royal Brunei Airlines', 'VG');
INSERT INTO airlines (id, name, country) VALUES ('BJ', 'Nouvel Air Tunisie', 'TN');
INSERT INTO airlines (id, name, country) VALUES ('BK', 'Potomac Air', 'US');
INSERT INTO airlines (id, name, country) VALUES ('BL', 'Pacific Airlines', 'VN');
INSERT INTO airlines (id, name, country) VALUES ('BM', 'Bayu Indonesia Air', 'ID');
INSERT INTO airlines (id, name, country) VALUES ('BN', 'Horizon Airlines', 'AU');
INSERT INTO airlines (id, name, country) VALUES ('BO', 'Bouraq Indonesia Airlines', 'ID');
INSERT INTO airlines (id, name, country) VALUES ('BP', 'Air Botswana', 'BW');
INSERT INTO airlines (id, name, country) VALUES ('BQ', 'Aeromar', 'DO');
INSERT INTO airlines (id, name, country) VALUES ('BR', 'EVA Air', 'TW');
INSERT INTO airlines (id, name, country) VALUES ('BS', 'British International Helicopters', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('BT', 'Air Baltic', 'LV');
INSERT INTO airlines (id, name, country) VALUES ('BV', 'Blue Panorama Airlines', 'IT');
INSERT INTO airlines (id, name, country) VALUES ('BW', 'Caribbean Airlines', 'TT');
INSERT INTO airlines (id, name, country) VALUES ('BX', 'Coast Air', 'NO');
INSERT INTO airlines (id, name, country) VALUES ('BZ', 'Blue Dart Aviation', 'IN');
INSERT INTO airlines (id, name, country) VALUES ('C0', 'Centralwings', 'PL');
INSERT INTO airlines (id, name, country) VALUES ('C3', 'ICAR Airlines', 'UA');
INSERT INTO airlines (id, name, country) VALUES ('C4', 'Zimex Aviation', 'CH');
INSERT INTO airlines (id, name, country) VALUES ('C5', 'CommutAir', 'US');
INSERT INTO airlines (id, name, country) VALUES ('C6', 'CanJet', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('C7', 'Rico Linhas Aéreas', 'BR');
INSERT INTO airlines (id, name, country) VALUES ('C8', 'Chicago Express', 'US');
INSERT INTO airlines (id, name, country) VALUES ('C9', 'Cirrus Airlines', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('CA', 'Air China', 'CN');
INSERT INTO airlines (id, name, country) VALUES ('CC', 'Air Atlanta Icelandic', 'IS');
INSERT INTO airlines (id, name, country) VALUES ('CD', 'Alliance Air', 'IN');
INSERT INTO airlines (id, name, country) VALUES ('CE', 'Nationwide Airlines', 'ZA');
INSERT INTO airlines (id, name, country) VALUES ('CF', 'City Airline', 'SE');
INSERT INTO airlines (id, name, country) VALUES ('CG', 'Airlines PNG', 'PN');
INSERT INTO airlines (id, name, country) VALUES ('CH', 'Bemidji Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('CI', 'China Airlines', 'TW');
INSERT INTO airlines (id, name, country) VALUES ('CJ', 'China Northern Airlines', 'CN');
INSERT INTO airlines (id, name, country) VALUES ('CK', 'China Cargo Airlines', 'CN');
INSERT INTO airlines (id, name, country) VALUES ('CL', 'Lufthansa CityLine', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('CM', 'Copa Airlines', 'PA');
INSERT INTO airlines (id, name, country) VALUES ('CN', 'Islands Nationair', 'PN');
INSERT INTO airlines (id, name, country) VALUES ('CO', 'Continental Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('CP', 'Canadian Airlines', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('CQ', 'Sunshine Express Airlines', 'AU');
INSERT INTO airlines (id, name, country) VALUES ('CR', 'OAG', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('CS', 'Continental Micronesia', 'US');
INSERT INTO airlines (id, name, country) VALUES ('CT', 'Civil Air Transport', 'TW');
INSERT INTO airlines (id, name, country) VALUES ('CU', 'Cubana de Aviación', 'CU');
INSERT INTO airlines (id, name, country) VALUES ('CV', 'Air Chathams', 'NC');
INSERT INTO airlines (id, name, country) VALUES ('CW', 'Air Marshall Islands', 'MH');
INSERT INTO airlines (id, name, country) VALUES ('CX', 'Cathay Pacific', 'HK');
INSERT INTO airlines (id, name, country) VALUES ('CY', 'Cyprus Airways', 'CY');
INSERT INTO airlines (id, name, country) VALUES ('CZ', 'China Southern Airlines', 'CN');
INSERT INTO airlines (id, name, country) VALUES ('D3', 'Daallo Airlines', 'DJ');
INSERT INTO airlines (id, name, country) VALUES ('D4', 'Alidaunia', 'IT');
INSERT INTO airlines (id, name, country) VALUES ('D5', 'Dauair', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('D6', 'Interair South Africa', 'ZA');
INSERT INTO airlines (id, name, country) VALUES ('D7', 'FlyAsianXpress', 'MY');
INSERT INTO airlines (id, name, country) VALUES ('D8', 'Djibouti Airlines', 'DJ');
INSERT INTO airlines (id, name, country) VALUES ('D9', 'Aeroflot-Don', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('DA', 'Air Georgia', 'GE');
INSERT INTO airlines (id, name, country) VALUES ('DB', 'Brit Air', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('DC', 'Golden Air', 'SE');
INSERT INTO airlines (id, name, country) VALUES ('DD', 'Nok Air', 'TH');
INSERT INTO airlines (id, name, country) VALUES ('DE', 'Condor Flugdienst', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('DG', 'South East Asian Airlines', 'PH');
INSERT INTO airlines (id, name, country) VALUES ('DH', 'Independence Air', 'US');
INSERT INTO airlines (id, name, country) VALUES ('DI', 'dba', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('DJ', 'Pacific Blue', 'NC');
INSERT INTO airlines (id, name, country) VALUES ('DK', 'Eastland Air', 'AU');
INSERT INTO airlines (id, name, country) VALUES ('DL', 'Delta Air Lines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('DM', 'Maersk', 'DK');
INSERT INTO airlines (id, name, country) VALUES ('DO', 'Dominicana de Aviación', 'DO');
INSERT INTO airlines (id, name, country) VALUES ('DP', 'First Choice Airways', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('DQ', 'Coastal Air', 'US');
INSERT INTO airlines (id, name, country) VALUES ('DR', 'Air Mediterranee', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('DT', 'TAAG Angola Airlines', 'AO');
INSERT INTO airlines (id, name, country) VALUES ('DU', 'Hemus Air', 'BG');
INSERT INTO airlines (id, name, country) VALUES ('DV', 'Lufttaxi Fluggesellschaft', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('DW', 'Aero-Charter Ukraine', 'UA');
INSERT INTO airlines (id, name, country) VALUES ('DX', 'DAT Danish Air Transport', 'DK');
INSERT INTO airlines (id, name, country) VALUES ('DY', 'Norwegian Air Shuttle', 'NO');
INSERT INTO airlines (id, name, country) VALUES ('E0', 'Eos Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('E1', 'Kampuchea Airlines', 'KH');
INSERT INTO airlines (id, name, country) VALUES ('E2', 'Rio Grande Air', 'US');
INSERT INTO airlines (id, name, country) VALUES ('E3', 'Domodedovo Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('E4', 'Aero Asia International', 'PK');
INSERT INTO airlines (id, name, country) VALUES ('E5', 'Samara Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('E6', 'Bringer Air Cargo Taxi Aereo', 'BR');
INSERT INTO airlines (id, name, country) VALUES ('E7', 'Estafeta Carga Aerea', 'MX');
INSERT INTO airlines (id, name, country) VALUES ('E8', 'Alpi Eagles', 'IT');
INSERT INTO airlines (id, name, country) VALUES ('E9', 'Boston-Maine Airways', 'US');
INSERT INTO airlines (id, name, country) VALUES ('EA', 'European Air Express', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('EB', 'Eagle Air', 'TZ');
INSERT INTO airlines (id, name, country) VALUES ('EC', 'Avialeasing Aviation Company', 'UZ');
INSERT INTO airlines (id, name, country) VALUES ('ED', 'Airblue', 'PK');
INSERT INTO airlines (id, name, country) VALUES ('EE', 'Aero Airlines', 'EE');
INSERT INTO airlines (id, name, country) VALUES ('EF', 'Far Eastern Air Transport', 'TW');
INSERT INTO airlines (id, name, country) VALUES ('EG', 'Japan Asia Airways', 'JP');
INSERT INTO airlines (id, name, country) VALUES ('EH', 'Air Nippon Network Co. Ltd.', 'JP');
INSERT INTO airlines (id, name, country) VALUES ('EI', 'Aer Lingus', 'IE');
INSERT INTO airlines (id, name, country) VALUES ('EJ', 'New England Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('EK', 'Emirates Airline', 'AE');
INSERT INTO airlines (id, name, country) VALUES ('EL', 'Air Nippon', 'JP');
INSERT INTO airlines (id, name, country) VALUES ('EM', 'Aero Benin', 'BJ');
INSERT INTO airlines (id, name, country) VALUES ('EN', 'Air Dolomiti', 'IT');
INSERT INTO airlines (id, name, country) VALUES ('EO', 'Express One International', 'US');
INSERT INTO airlines (id, name, country) VALUES ('EP', 'Hewa Bora Airways', 'CD');
INSERT INTO airlines (id, name, country) VALUES ('EQ', 'Iran Aseman Airlines', 'IR');
INSERT INTO airlines (id, name, country) VALUES ('ER', 'TAME', 'EC');
INSERT INTO airlines (id, name, country) VALUES ('ES', 'Astar Air Cargo', 'US');
INSERT INTO airlines (id, name, country) VALUES ('ET', 'DHL International', 'BH');
INSERT INTO airlines (id, name, country) VALUES ('EU', 'Ethiopian Airlines', 'ET');
INSERT INTO airlines (id, name, country) VALUES ('EV', 'Empresa Ecuatoriana De Aviacion', 'EC');
INSERT INTO airlines (id, name, country) VALUES ('EW', 'Atlantic Southeast Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('EX', 'Eurowings', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('EY', 'Air Santo Domingo', 'DO');
INSERT INTO airlines (id, name, country) VALUES ('EZ', 'Etihad Airways', 'AE');
INSERT INTO airlines (id, name, country) VALUES ('F2', 'Sun Air of Scandinavia', 'DK');
INSERT INTO airlines (id, name, country) VALUES ('F3', 'Fly Air', 'TR');
INSERT INTO airlines (id, name, country) VALUES ('F4', 'Faso Airways', 'BF');
INSERT INTO airlines (id, name, country) VALUES ('F5', 'Albarka Air', 'NG');
INSERT INTO airlines (id, name, country) VALUES ('F6', 'Cosmic Air', 'NP');
INSERT INTO airlines (id, name, country) VALUES ('F7', 'Faroejet', 'FO');
INSERT INTO airlines (id, name, country) VALUES ('F9', 'Flybaboo', 'CH');
INSERT INTO airlines (id, name, country) VALUES ('FA', 'Frontier Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('FB', 'Safair', 'ZA');
INSERT INTO airlines (id, name, country) VALUES ('FC', 'Bulgaria Air', 'BG');
INSERT INTO airlines (id, name, country) VALUES ('FD', 'Finncomm Airlines', 'FI');
INSERT INTO airlines (id, name, country) VALUES ('FE', 'Thai AirAsia', 'TH');
INSERT INTO airlines (id, name, country) VALUES ('FF', 'Primaris Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('FG', 'Airshop', 'NL');
INSERT INTO airlines (id, name, country) VALUES ('FH', 'Ariana Afghan Airlines', 'AF');
INSERT INTO airlines (id, name, country) VALUES ('FI', 'Futura International Airways', 'ES');
INSERT INTO airlines (id, name, country) VALUES ('FJ', 'Icelandair', 'IS');
INSERT INTO airlines (id, name, country) VALUES ('FK', 'Air Pacific', 'FJ');
INSERT INTO airlines (id, name, country) VALUES ('FL', 'Africa West', 'TG');
INSERT INTO airlines (id, name, country) VALUES ('FM', 'AirTran Airways', 'US');
INSERT INTO airlines (id, name, country) VALUES ('FN', 'Shanghai Airlines', 'CN');
INSERT INTO airlines (id, name, country) VALUES ('FO', 'Regional Air Lines', 'MA');
INSERT INTO airlines (id, name, country) VALUES ('FP', 'Airlines of Tasmania', 'AU');
INSERT INTO airlines (id, name, country) VALUES ('FQ', 'Freedom Air', 'US');
INSERT INTO airlines (id, name, country) VALUES ('FR', 'Thomas Cook Airlines', 'BE');
INSERT INTO airlines (id, name, country) VALUES ('FS', 'Ryanair', 'IE');
INSERT INTO airlines (id, name, country) VALUES ('FT', 'Servicios de Transportes Aéreos Fueguinos', 'AR');
INSERT INTO airlines (id, name, country) VALUES ('FV', 'Siem Reap Airways', 'KH');
INSERT INTO airlines (id, name, country) VALUES ('FW', 'Rossiya', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('FX', 'Ibex Airlines', 'JP');
INSERT INTO airlines (id, name, country) VALUES ('FY', 'Firefly', 'MY');
INSERT INTO airlines (id, name, country) VALUES ('G0', 'Northwest Regional Airlines', 'AU');
INSERT INTO airlines (id, name, country) VALUES ('G1', 'Ghana International Airlines', 'GH');
INSERT INTO airlines (id, name, country) VALUES ('G2', 'Gorkha Airlines', 'NP');
INSERT INTO airlines (id, name, country) VALUES ('G3', 'City Connexion Airlines', 'BI');
INSERT INTO airlines (id, name, country) VALUES ('G4', 'Gol Transportes Aéreos', 'BR');
INSERT INTO airlines (id, name, country) VALUES ('G5', 'Avirex', 'GA');
INSERT INTO airlines (id, name, country) VALUES ('G6', 'Allegiant Air', 'US');
INSERT INTO airlines (id, name, country) VALUES ('G7', 'Guine Bissaur Airlines', 'GW');
INSERT INTO airlines (id, name, country) VALUES ('G8', 'Air Service Gabon', 'GA');
INSERT INTO airlines (id, name, country) VALUES ('G9', 'Gujarat Airways', 'IN');
INSERT INTO airlines (id, name, country) VALUES ('GA', 'Air Arabia', 'AE');
INSERT INTO airlines (id, name, country) VALUES ('GB', 'Garuda Indonesia', 'ID');
INSERT INTO airlines (id, name, country) VALUES ('GC', 'ABX Air', 'US');
INSERT INTO airlines (id, name, country) VALUES ('GD', 'Gambia International Airlines', 'GM');
INSERT INTO airlines (id, name, country) VALUES ('GE', 'Air Alpha Greenland', 'DK');
INSERT INTO airlines (id, name, country) VALUES ('GF', 'TransAsia Airways', 'TW');
INSERT INTO airlines (id, name, country) VALUES ('GG', 'Air Guyane', 'GF');
INSERT INTO airlines (id, name, country) VALUES ('GH', 'Air Comores International', 'KM');
INSERT INTO airlines (id, name, country) VALUES ('GI', 'Ghana Airways', 'GH');
INSERT INTO airlines (id, name, country) VALUES ('GJ', 'Itek Air', 'KG');
INSERT INTO airlines (id, name, country) VALUES ('GK', 'Eurofly', 'IT');
INSERT INTO airlines (id, name, country) VALUES ('GL', 'Air Greenland', 'DK');
INSERT INTO airlines (id, name, country) VALUES ('GM', 'Miami Air International', 'US');
INSERT INTO airlines (id, name, country) VALUES ('GN', 'Air Slovakia', 'SK');
INSERT INTO airlines (id, name, country) VALUES ('GO', 'Air Gabon', 'GA');
INSERT INTO airlines (id, name, country) VALUES ('GP', 'Kuzu Airlines Cargo', 'TR');
INSERT INTO airlines (id, name, country) VALUES ('GQ', 'Palau Trans Pacific Airline', 'PW');
INSERT INTO airlines (id, name, country) VALUES ('GR', 'Aurigny Air Services', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('GS', 'Air Foyle', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('GT', 'Grant Aviation', 'US');
INSERT INTO airlines (id, name, country) VALUES ('GU', 'JetX Airlines', 'IS');
INSERT INTO airlines (id, name, country) VALUES ('GV', 'GB Airways', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('GW', 'Aero Flight', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('GX', 'Kuban Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('GY', 'Pacificair', 'PH');
INSERT INTO airlines (id, name, country) VALUES ('GZ', 'Tri-MG Intra Asia Airlines', 'ID');
INSERT INTO airlines (id, name, country) VALUES ('H2', 'Rotation International Air Services', 'ET');
INSERT INTO airlines (id, name, country) VALUES ('H3', 'Hola Airlines', 'ES');
INSERT INTO airlines (id, name, country) VALUES ('H4', 'Sky Airline', 'CL');
INSERT INTO airlines (id, name, country) VALUES ('H5', 'Inter Islands Airlines', 'CV');
INSERT INTO airlines (id, name, country) VALUES ('H6', 'Mavial Magadan Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('H7', 'Hageland Aviation Services', 'US');
INSERT INTO airlines (id, name, country) VALUES ('H8', 'Eagle Air', 'UG');
INSERT INTO airlines (id, name, country) VALUES ('H9', 'Air D''Ayiti', 'HT');
INSERT INTO airlines (id, name, country) VALUES ('HA', 'Pegasus Airlines', 'TR');
INSERT INTO airlines (id, name, country) VALUES ('HB', 'Hawaiian Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('HC', 'Harbor Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('HD', 'Air Holland', 'NL');
INSERT INTO airlines (id, name, country) VALUES ('HE', 'Hokkaido International Airlines', 'JP');
INSERT INTO airlines (id, name, country) VALUES ('HF', 'Luftfahrtgesellschaft Walter', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('HG', 'Hapagfly', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('HH', 'Niki', 'AT');
INSERT INTO airlines (id, name, country) VALUES ('HI', 'Pearl Airways', 'HT');
INSERT INTO airlines (id, name, country) VALUES ('HJ', 'Hope Air', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('HK', 'Asian Express Airlines', 'AU');
INSERT INTO airlines (id, name, country) VALUES ('HM', 'Four Star Aviation / Four Star Cargo', 'US');
INSERT INTO airlines (id, name, country) VALUES ('HN', 'Air Seychelles', 'SC');
INSERT INTO airlines (id, name, country) VALUES ('HO', 'Heavylift Cargo Airlines', 'AU');
INSERT INTO airlines (id, name, country) VALUES ('HP', 'Antinea Airlines', 'DZ');
INSERT INTO airlines (id, name, country) VALUES ('HQ', 'Phoenix Airways', 'CH');
INSERT INTO airlines (id, name, country) VALUES ('HR', 'Harmony Airways', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('HT', 'Hahn Air', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('HU', 'Aeromist-Kharkiv', 'UA');
INSERT INTO airlines (id, name, country) VALUES ('HV', 'Hainan Airlines', 'CN');
INSERT INTO airlines (id, name, country) VALUES ('HW', 'Transavia Holland', 'NL');
INSERT INTO airlines (id, name, country) VALUES ('HX', 'Hello', 'CH');
INSERT INTO airlines (id, name, country) VALUES ('HY', 'North-Wright Airways', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('HZ', 'Uzbekistan Airways', 'UZ');
INSERT INTO airlines (id, name, country) VALUES ('I0', 'Great Wall Airlines', 'CN');
INSERT INTO airlines (id, name, country) VALUES ('I1', 'Paramount Airways', 'IN');
INSERT INTO airlines (id, name, country) VALUES ('I2', 'Imair Airlines', 'AZ');
INSERT INTO airlines (id, name, country) VALUES ('I4', 'Sat Airlines', 'KZ');
INSERT INTO airlines (id, name, country) VALUES ('I6', 'Interstate Airline', 'NL');
INSERT INTO airlines (id, name, country) VALUES ('I7', 'Sky Eyes', 'TH');
INSERT INTO airlines (id, name, country) VALUES ('I9', 'Air Italy', 'IT');
INSERT INTO airlines (id, name, country) VALUES ('IA', 'Indigo', 'US');
INSERT INTO airlines (id, name, country) VALUES ('IB', 'Iraqi Airways', 'IQ');
INSERT INTO airlines (id, name, country) VALUES ('IC', 'Iberia Airlines', 'ES');
INSERT INTO airlines (id, name, country) VALUES ('ID', 'Indian Airlines', 'IN');
INSERT INTO airlines (id, name, country) VALUES ('IE', 'Interlink Airlines', 'ZA');
INSERT INTO airlines (id, name, country) VALUES ('IF', 'Solomon Airlines', 'SB');
INSERT INTO airlines (id, name, country) VALUES ('IG', 'Islas Airways', 'ES');
INSERT INTO airlines (id, name, country) VALUES ('IH', 'Meridiana', 'IT');
INSERT INTO airlines (id, name, country) VALUES ('II', 'Falcon Aviation', 'SE');
INSERT INTO airlines (id, name, country) VALUES ('IJ', 'IBC Airways', 'US');
INSERT INTO airlines (id, name, country) VALUES ('IK', 'InteliJet Airways', 'CO');
INSERT INTO airlines (id, name, country) VALUES ('IM', 'Lankair', 'LK');
INSERT INTO airlines (id, name, country) VALUES ('IN', 'Menajet', 'LB');
INSERT INTO airlines (id, name, country) VALUES ('IO', 'MAT Macedonian Airlines', 'MK');
INSERT INTO airlines (id, name, country) VALUES ('IP', 'Indonesian Airlines', 'ID');
INSERT INTO airlines (id, name, country) VALUES ('IQ', 'Atyrau Air Ways', 'KZ');
INSERT INTO airlines (id, name, country) VALUES ('IR', 'Augsburg Airways', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('IS', 'Iran Air', 'IR');
INSERT INTO airlines (id, name, country) VALUES ('IT', 'Irtysh Airlines', 'UZ');
INSERT INTO airlines (id, name, country) VALUES ('IV', 'Kingfisher Airlines', 'IN');
INSERT INTO airlines (id, name, country) VALUES ('IW', 'Wind Jet', 'IT');
INSERT INTO airlines (id, name, country) VALUES ('IX', 'AOM French Airlines', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('IY', 'Air India Express', 'IN');
INSERT INTO airlines (id, name, country) VALUES ('IZ', 'Yemenia', 'YE');
INSERT INTO airlines (id, name, country) VALUES ('J0', 'Jazeera Airways', 'KW');
INSERT INTO airlines (id, name, country) VALUES ('J1', 'Berjaya Air', 'MY');
INSERT INTO airlines (id, name, country) VALUES ('J2', 'Arkia Israel Airlines', 'IL');
INSERT INTO airlines (id, name, country) VALUES ('J3', 'Azerbaijan Airlines', 'AZ');
INSERT INTO airlines (id, name, country) VALUES ('J4', 'Northwestern Air', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('J6', 'Buffalo Airways', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('J7', 'Centre-Avia', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('J8', 'ValuJet Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('J9', 'Guinee Airlines', 'GN');
INSERT INTO airlines (id, name, country) VALUES ('JA', 'Air Bosna', 'BA');
INSERT INTO airlines (id, name, country) VALUES ('JB', 'B&H Airlines', 'BA');
INSERT INTO airlines (id, name, country) VALUES ('JC', 'Helijet', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('JD', 'Mango', 'ZA');
INSERT INTO airlines (id, name, country) VALUES ('JE', 'JAL Express', 'JP');
INSERT INTO airlines (id, name, country) VALUES ('JF', 'Jetairfly', 'BE');
INSERT INTO airlines (id, name, country) VALUES ('JG', 'Midway Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('JH', 'L.A.B. Flying Service', 'US');
INSERT INTO airlines (id, name, country) VALUES ('JI', 'Nordeste Linhas Aereas Regionais', 'BR');
INSERT INTO airlines (id, name, country) VALUES ('JJ', 'Aviogenex', 'RS');
INSERT INTO airlines (id, name, country) VALUES ('JK', 'TAM Brazilian Airlines', 'BR');
INSERT INTO airlines (id, name, country) VALUES ('JL', 'Spanair', 'ES');
INSERT INTO airlines (id, name, country) VALUES ('JM', 'Japan Airlines Domestic', 'JP');
INSERT INTO airlines (id, name, country) VALUES ('JN', 'Air Jamaica', 'JM');
INSERT INTO airlines (id, name, country) VALUES ('JO', 'Excel Airways', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('JP', 'JALways', 'JP');
INSERT INTO airlines (id, name, country) VALUES ('JQ', 'Adria Airways', 'SI');
INSERT INTO airlines (id, name, country) VALUES ('JR', 'Jetstar Airways', 'AU');
INSERT INTO airlines (id, name, country) VALUES ('JS', 'Aero California', 'MX');
INSERT INTO airlines (id, name, country) VALUES ('JT', 'Air Koryo', 'CZ');
INSERT INTO airlines (id, name, country) VALUES ('JU', 'Lion Mentari Airlines', 'ID');
INSERT INTO airlines (id, name, country) VALUES ('JV', 'Jat Airways', 'RS');
INSERT INTO airlines (id, name, country) VALUES ('JW', 'Bearskin Lake Air Service', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('JX', 'Arrow Air', 'US');
INSERT INTO airlines (id, name, country) VALUES ('JY', 'Jett8 Airlines Cargo', 'SG');
INSERT INTO airlines (id, name, country) VALUES ('JZ', 'Air Turks and Caicos', 'TC');
INSERT INTO airlines (id, name, country) VALUES ('K2', 'Skyways Express', 'SE');
INSERT INTO airlines (id, name, country) VALUES ('K4', 'Eurolot', 'PL');
INSERT INTO airlines (id, name, country) VALUES ('K5', 'Kalitta Air', 'US');
INSERT INTO airlines (id, name, country) VALUES ('K6', 'Wings of Alaska', 'US');
INSERT INTO airlines (id, name, country) VALUES ('K8', 'Bravo Air Congo', 'CD');
INSERT INTO airlines (id, name, country) VALUES ('K9', 'Airlink Zambia', 'ZM');
INSERT INTO airlines (id, name, country) VALUES ('KA', 'Krylo Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('KB', 'Dragonair, Hong Kong Dragon Airlines', 'HK');
INSERT INTO airlines (id, name, country) VALUES ('KC', 'Druk Air', 'BT');
INSERT INTO airlines (id, name, country) VALUES ('KD', 'Air Astana', 'KZ');
INSERT INTO airlines (id, name, country) VALUES ('KE', 'KD Avia', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('KF', 'Korean Air', 'QA');
INSERT INTO airlines (id, name, country) VALUES ('KG', 'Blue1', 'FI');
INSERT INTO airlines (id, name, country) VALUES ('KI', 'LAI - Linea Aerea IAACA', 'VE');
INSERT INTO airlines (id, name, country) VALUES ('KJ', 'Adam Air', 'ID');
INSERT INTO airlines (id, name, country) VALUES ('KK', 'British Mediterranean Airways', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('KL', 'Atlasjet', 'TR');
INSERT INTO airlines (id, name, country) VALUES ('KM', 'KLM Royal Dutch Airlines', 'NL');
INSERT INTO airlines (id, name, country) VALUES ('KN', 'Air Malta', 'MT');
INSERT INTO airlines (id, name, country) VALUES ('KO', 'China United Airlines', 'CN');
INSERT INTO airlines (id, name, country) VALUES ('KP', 'Alaska Central Express', 'US');
INSERT INTO airlines (id, name, country) VALUES ('KQ', 'Kiwi International Air Lines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('KR', 'Kenya Airways', 'KE');
INSERT INTO airlines (id, name, country) VALUES ('KS', 'Comores Airlines', 'KM');
INSERT INTO airlines (id, name, country) VALUES ('KU', 'Peninsula Airways', 'US');
INSERT INTO airlines (id, name, country) VALUES ('KV', 'Kuwait Airways', 'KW');
INSERT INTO airlines (id, name, country) VALUES ('KX', 'Kavminvodyavia', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('KY', 'Cayman Airways', 'KY');
INSERT INTO airlines (id, name, country) VALUES ('KZ', 'Kibris Türk Hava', 'TR');
INSERT INTO airlines (id, name, country) VALUES ('L1', 'Nippon Cargo Airlines', 'JP');
INSERT INTO airlines (id, name, country) VALUES ('L2', 'Lufthansa Systems', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('L3', 'Lynden Air Cargo', 'US');
INSERT INTO airlines (id, name, country) VALUES ('L4', 'LTU Austria', 'AT');
INSERT INTO airlines (id, name, country) VALUES ('L5', 'Lynx Aviation', 'US');
INSERT INTO airlines (id, name, country) VALUES ('L6', 'Lufttransport', 'NO');
INSERT INTO airlines (id, name, country) VALUES ('L7', 'Tbilaviamsheni', 'GE');
INSERT INTO airlines (id, name, country) VALUES ('L8', 'Linea Aerea SAPSA', 'CL');
INSERT INTO airlines (id, name, country) VALUES ('L9', 'Air Luxor GB', 'GW');
INSERT INTO airlines (id, name, country) VALUES ('LA', 'Teamline Air', 'AT');
INSERT INTO airlines (id, name, country) VALUES ('LB', 'LAN Airlines', 'CL');
INSERT INTO airlines (id, name, country) VALUES ('LC', 'Lloyd Aereo Boliviano', 'BO');
INSERT INTO airlines (id, name, country) VALUES ('LD', 'Varig Logística', 'BR');
INSERT INTO airlines (id, name, country) VALUES ('LF', 'Linea Turistica Aerotuy', 'VE');
INSERT INTO airlines (id, name, country) VALUES ('LG', 'FlyNordic', 'SE');
INSERT INTO airlines (id, name, country) VALUES ('LH', 'Luxair', 'LU');
INSERT INTO airlines (id, name, country) VALUES ('LI', 'Lufthansa Cargo', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('LJ', 'Leeward Islands Air Transport', 'AG');
INSERT INTO airlines (id, name, country) VALUES ('LK', 'Sierra National Airlines', 'SL');
INSERT INTO airlines (id, name, country) VALUES ('LL', 'Air Luxor', 'PT');
INSERT INTO airlines (id, name, country) VALUES ('LM', 'Allegro', 'MX');
INSERT INTO airlines (id, name, country) VALUES ('LN', 'Livingston', 'IT');
INSERT INTO airlines (id, name, country) VALUES ('LO', 'Libyan Arab Airlines', 'LY');
INSERT INTO airlines (id, name, country) VALUES ('LP', 'LOT Polish Airlines', 'PL');
INSERT INTO airlines (id, name, country) VALUES ('LQ', 'LAN Peru', 'PE');
INSERT INTO airlines (id, name, country) VALUES ('LR', 'Lebanese Air Transport', 'LB');
INSERT INTO airlines (id, name, country) VALUES ('LS', 'LACSA', 'CR');
INSERT INTO airlines (id, name, country) VALUES ('LT', 'Jet2.com', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('LU', 'LTU International', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('LV', 'LAN Express', 'CL');
INSERT INTO airlines (id, name, country) VALUES ('LW', 'Albanian Airlines', 'AL');
INSERT INTO airlines (id, name, country) VALUES ('LX', 'Pacific Wings', 'US');
INSERT INTO airlines (id, name, country) VALUES ('LY', 'Swiss International Air Lines', 'CH');
INSERT INTO airlines (id, name, country) VALUES ('LZ', 'El Al Israel Airlines', 'IL');
INSERT INTO airlines (id, name, country) VALUES ('M3', 'Mahfooz Aviation', 'GM');
INSERT INTO airlines (id, name, country) VALUES ('M4', 'North Flying', 'DK');
INSERT INTO airlines (id, name, country) VALUES ('M5', 'Nova Airline', 'SD');
INSERT INTO airlines (id, name, country) VALUES ('M6', 'Kenmore Air', 'US');
INSERT INTO airlines (id, name, country) VALUES ('M7', 'Amerijet International', 'US');
INSERT INTO airlines (id, name, country) VALUES ('M9', 'Tropical Airways', 'HT');
INSERT INTO airlines (id, name, country) VALUES ('MA', 'Motor Sich', 'UA');
INSERT INTO airlines (id, name, country) VALUES ('MB', 'Malév Hungarian Airlines', 'HU');
INSERT INTO airlines (id, name, country) VALUES ('MC', 'MNG Airlines', 'TR');
INSERT INTO airlines (id, name, country) VALUES ('MD', 'Air Mobility Command', 'US');
INSERT INTO airlines (id, name, country) VALUES ('ME', 'Air Madagascar', 'MG');
INSERT INTO airlines (id, name, country) VALUES ('MF', 'Middle East Airlines', 'LB');
INSERT INTO airlines (id, name, country) VALUES ('MG', 'Xiamen Airlines', 'CN');
INSERT INTO airlines (id, name, country) VALUES ('MH', 'Champion Air', 'US');
INSERT INTO airlines (id, name, country) VALUES ('MI', 'Malaysia Airlines', 'MY');
INSERT INTO airlines (id, name, country) VALUES ('MJ', 'SilkAir', 'SG');
INSERT INTO airlines (id, name, country) VALUES ('MK', 'Líneas Aéreas Privadas Argentinas', 'AR');
INSERT INTO airlines (id, name, country) VALUES ('ML', 'Air Mauritius', 'MU');
INSERT INTO airlines (id, name, country) VALUES ('MM', 'African Transport Trading and Investment Company', 'SD');
INSERT INTO airlines (id, name, country) VALUES ('MN', 'SAM Colombia', 'CO');
INSERT INTO airlines (id, name, country) VALUES ('MO', 'Comair', 'ZA');
INSERT INTO airlines (id, name, country) VALUES ('MP', 'Calm Air', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('MQ', 'Martinair', 'NL');
INSERT INTO airlines (id, name, country) VALUES ('MR', 'American Eagle Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('MS', 'Air Mauritanie', 'MR');
INSERT INTO airlines (id, name, country) VALUES ('MT', 'Egyptair', 'EG');
INSERT INTO airlines (id, name, country) VALUES ('MU', 'Thomas Cook Airlines', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('MV', 'China Eastern Airlines', 'CN');
INSERT INTO airlines (id, name, country) VALUES ('MW', 'Armenian International Airways', 'AM');
INSERT INTO airlines (id, name, country) VALUES ('MX', 'Maya Island Air', 'BZ');
INSERT INTO airlines (id, name, country) VALUES ('MY', 'Mexicana de Aviación', 'MX');
INSERT INTO airlines (id, name, country) VALUES ('MZ', 'Midwest Airlines (Egypt)', 'EG');
INSERT INTO airlines (id, name, country) VALUES ('N2', 'Merpati Nusantara Airlines', 'ID');
INSERT INTO airlines (id, name, country) VALUES ('N3', 'Kabo Air', 'NG');
INSERT INTO airlines (id, name, country) VALUES ('N4', 'Omskavia Airline', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('N5', 'National Airlines', 'CL');
INSERT INTO airlines (id, name, country) VALUES ('N6', 'Skagway Air Service', 'US');
INSERT INTO airlines (id, name, country) VALUES ('N7', 'Nuevo Continente', 'PE');
INSERT INTO airlines (id, name, country) VALUES ('N8', 'National Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('N9', 'Hong Kong Airlines', 'HK');
INSERT INTO airlines (id, name, country) VALUES ('NA', 'North Coast Aviation', 'PN');
INSERT INTO airlines (id, name, country) VALUES ('NB', 'National Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('NC', 'Sterling Airlines', 'DK');
INSERT INTO airlines (id, name, country) VALUES ('NE', 'Northern Air Cargo', 'US');
INSERT INTO airlines (id, name, country) VALUES ('NF', 'SkyEurope', 'SK');
INSERT INTO airlines (id, name, country) VALUES ('NG', 'Air Vanuatu', 'VU');
INSERT INTO airlines (id, name, country) VALUES ('NH', 'Lauda Air', 'AT');
INSERT INTO airlines (id, name, country) VALUES ('NI', 'All Nippon Airways', 'JP');
INSERT INTO airlines (id, name, country) VALUES ('NK', 'Portugalia', 'PT');
INSERT INTO airlines (id, name, country) VALUES ('NL', 'Spirit Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('NM', 'Shaheen Air International', 'PK');
INSERT INTO airlines (id, name, country) VALUES ('NN', 'Mount Cook Airlines', 'NC');
INSERT INTO airlines (id, name, country) VALUES ('NO', 'VIM Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('NQ', 'Neos', 'IT');
INSERT INTO airlines (id, name, country) VALUES ('NR', 'Air Japan', 'JP');
INSERT INTO airlines (id, name, country) VALUES ('NT', 'Pamir Airways', 'AF');
INSERT INTO airlines (id, name, country) VALUES ('NU', 'Binter Canarias', 'ES');
INSERT INTO airlines (id, name, country) VALUES ('NV', 'Japan Transocean Air', 'JP');
INSERT INTO airlines (id, name, country) VALUES ('NW', 'Air Central', 'JP');
INSERT INTO airlines (id, name, country) VALUES ('NX', 'Northwest Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('NY', 'Air Macau', 'LU');
INSERT INTO airlines (id, name, country) VALUES ('NZ', 'Air Iceland', 'IS');
INSERT INTO airlines (id, name, country) VALUES ('O2', 'Eagle Airways', 'NC');
INSERT INTO airlines (id, name, country) VALUES ('O6', 'Oceanic Airlines', 'GN');
INSERT INTO airlines (id, name, country) VALUES ('O7', 'Oceanair', 'BR');
INSERT INTO airlines (id, name, country) VALUES ('O8', 'Ozjet Airlines', 'AU');
INSERT INTO airlines (id, name, country) VALUES ('OA', 'Oasis Hong Kong Airlines', 'HK');
INSERT INTO airlines (id, name, country) VALUES ('OB', 'Olympic Airlines', 'GR');
INSERT INTO airlines (id, name, country) VALUES ('OE', 'Astrakhan Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('OF', 'Asia Overnight Express', 'PH');
INSERT INTO airlines (id, name, country) VALUES ('OJ', 'Comair', 'US');
INSERT INTO airlines (id, name, country) VALUES ('OK', 'Overland Airways', 'NG');
INSERT INTO airlines (id, name, country) VALUES ('OL', 'Czech Airlines', 'CZ');
INSERT INTO airlines (id, name, country) VALUES ('OM', 'Ostfriesische Lufttransport', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('ON', 'MIAT Mongolian Airlines', 'MN');
INSERT INTO airlines (id, name, country) VALUES ('OO', 'Our Airline', 'NR');
INSERT INTO airlines (id, name, country) VALUES ('OP', 'SkyWest Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('OR', 'Chalk''s Ocean Airways', 'US');
INSERT INTO airlines (id, name, country) VALUES ('OS', 'Arkefly', 'NL');
INSERT INTO airlines (id, name, country) VALUES ('OT', 'Austrian Airlines', 'AT');
INSERT INTO airlines (id, name, country) VALUES ('OU', 'Aeropelican Air Services', 'AU');
INSERT INTO airlines (id, name, country) VALUES ('OV', 'Croatia Airlines', 'CI');
INSERT INTO airlines (id, name, country) VALUES ('OW', 'Estonian Air', 'EE');
INSERT INTO airlines (id, name, country) VALUES ('OX', 'Executive Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('OY', 'Orient Thai Airlines', 'TH');
INSERT INTO airlines (id, name, country) VALUES ('OZ', 'Omni Air International', 'US');
INSERT INTO airlines (id, name, country) VALUES ('P0', 'Ozark Air Lines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('P5', 'Proflight Commuter Services', 'ZM');
INSERT INTO airlines (id, name, country) VALUES ('P7', 'AeroRepública', 'CO');
INSERT INTO airlines (id, name, country) VALUES ('P8', 'Russian Sky Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('P9', 'Pantanal Linhas Aéreas', 'BR');
INSERT INTO airlines (id, name, country) VALUES ('PA', 'Perm Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('PC', 'Pan American World Airways', 'US');
INSERT INTO airlines (id, name, country) VALUES ('PD', 'Continental Airways', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('PE', 'Porter Airlines', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('PF', 'Air Europe', 'IT');
INSERT INTO airlines (id, name, country) VALUES ('PG', 'Palestinian Airlines', 'EG');
INSERT INTO airlines (id, name, country) VALUES ('PH', 'Bangkok Airways', 'TH');
INSERT INTO airlines (id, name, country) VALUES ('PI', 'Polynesian Airlines', 'WS');
INSERT INTO airlines (id, name, country) VALUES ('PJ', 'Sun Air (Fiji)', 'FJ');
INSERT INTO airlines (id, name, country) VALUES ('PK', 'Air Saint Pierre', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('PL', 'Pakistan International Airlines', 'PK');
INSERT INTO airlines (id, name, country) VALUES ('PM', 'Airstars', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('PN', 'Tropic Air', 'BZ');
INSERT INTO airlines (id, name, country) VALUES ('PO', 'Pan American Airways', 'US');
INSERT INTO airlines (id, name, country) VALUES ('PQ', 'Polar Air Cargo', 'US');
INSERT INTO airlines (id, name, country) VALUES ('PR', 'Panafrican Airways', 'IT');
INSERT INTO airlines (id, name, country) VALUES ('PS', 'Philippine Airlines', 'PH');
INSERT INTO airlines (id, name, country) VALUES ('PT', 'Ukraine International Airlines', 'UA');
INSERT INTO airlines (id, name, country) VALUES ('PU', 'West Air Sweden', 'SE');
INSERT INTO airlines (id, name, country) VALUES ('PV', 'PLUNA', 'UY');
INSERT INTO airlines (id, name, country) VALUES ('PW', 'PAN Air', 'ES');
INSERT INTO airlines (id, name, country) VALUES ('PX', 'Precision Air', 'TZ');
INSERT INTO airlines (id, name, country) VALUES ('PY', 'Air Niugini', 'PN');
INSERT INTO airlines (id, name, country) VALUES ('PZ', 'Surinam Airways', 'SR');
INSERT INTO airlines (id, name, country) VALUES ('Q3', 'TAM Mercosur', 'PY');
INSERT INTO airlines (id, name, country) VALUES ('Q4', 'Zambian Airways', 'ZM');
INSERT INTO airlines (id, name, country) VALUES ('Q5', 'Mastertop Linhas Aereas', 'BR');
INSERT INTO airlines (id, name, country) VALUES ('Q6', '40-Mile Air', 'US');
INSERT INTO airlines (id, name, country) VALUES ('Q8', 'Aero Condor Peru', 'PE');
INSERT INTO airlines (id, name, country) VALUES ('Q9', 'Pacific East Asia Cargo Airlines', 'PH');
INSERT INTO airlines (id, name, country) VALUES ('QB', 'Afrinat International Airlines', 'GM');
INSERT INTO airlines (id, name, country) VALUES ('QC', 'Georgian National Airlines', 'GE');
INSERT INTO airlines (id, name, country) VALUES ('QD', 'Air Corridor', 'MZ');
INSERT INTO airlines (id, name, country) VALUES ('QE', 'Air Class Lineas Aereas', 'UY');
INSERT INTO airlines (id, name, country) VALUES ('QF', 'Crossair Europe', 'CH');
INSERT INTO airlines (id, name, country) VALUES ('QH', 'Sunstate Airlines', 'AU');
INSERT INTO airlines (id, name, country) VALUES ('QI', 'Kyrgyzstan', 'KG');
INSERT INTO airlines (id, name, country) VALUES ('QJ', 'Cimber Air', 'DK');
INSERT INTO airlines (id, name, country) VALUES ('QK', 'Jet Airways', 'US');
INSERT INTO airlines (id, name, country) VALUES ('QL', 'Air Canada Jazz', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('QM', 'Aero Lanka', 'LK');
INSERT INTO airlines (id, name, country) VALUES ('QN', 'Air Malawi', 'MW');
INSERT INTO airlines (id, name, country) VALUES ('QO', 'Air Armenia', 'AM');
INSERT INTO airlines (id, name, country) VALUES ('QQ', 'Origin Pacific Airways', 'NC');
INSERT INTO airlines (id, name, country) VALUES ('QR', 'Reno Air', 'US');
INSERT INTO airlines (id, name, country) VALUES ('QS', 'Qatar Airways', 'QA');
INSERT INTO airlines (id, name, country) VALUES ('QT', 'Travel Service', 'CZ');
INSERT INTO airlines (id, name, country) VALUES ('QU', 'TAMPA', 'CO');
INSERT INTO airlines (id, name, country) VALUES ('QV', 'East African', 'UG');
INSERT INTO airlines (id, name, country) VALUES ('QW', 'Lao Airlines', 'KG');
INSERT INTO airlines (id, name, country) VALUES ('QX', 'Blue Wings', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('QY', 'Horizon Air', 'US');
INSERT INTO airlines (id, name, country) VALUES ('QZ', 'European Air Transport', 'BE');
INSERT INTO airlines (id, name, country) VALUES ('R0', 'Indonesia AirAsia', 'ID');
INSERT INTO airlines (id, name, country) VALUES ('R1', 'Royal Airlines', 'PK');
INSERT INTO airlines (id, name, country) VALUES ('R3', 'Orenburg Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('R5', 'Aircompany Yakutia', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('R6', 'Malta Air Charter', 'MT');
INSERT INTO airlines (id, name, country) VALUES ('R7', 'RACSA', 'GT');
INSERT INTO airlines (id, name, country) VALUES ('R8', 'Aserca Airlines', 'VE');
INSERT INTO airlines (id, name, country) VALUES ('R9', 'Kyrgyzstan Airlines', 'KG');
INSERT INTO airlines (id, name, country) VALUES ('RA', 'Camai Air', 'US');
INSERT INTO airlines (id, name, country) VALUES ('RB', 'Royal Nepal Airlines', 'NP');
INSERT INTO airlines (id, name, country) VALUES ('RC', 'Syrian Arab Airlines', 'SY');
INSERT INTO airlines (id, name, country) VALUES ('RD', 'Atlantic Airways', 'FO');
INSERT INTO airlines (id, name, country) VALUES ('RE', 'Ryan International Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('RF', 'Aer Arann', 'IE');
INSERT INTO airlines (id, name, country) VALUES ('RG', 'Florida West International Airways', 'US');
INSERT INTO airlines (id, name, country) VALUES ('RH', 'VRG Linhas Aereas', 'BR');
INSERT INTO airlines (id, name, country) VALUES ('RI', 'Republic Express Airlines', 'ID');
INSERT INTO airlines (id, name, country) VALUES ('RJ', 'Mandala Airlines', 'ID');
INSERT INTO airlines (id, name, country) VALUES ('RK', 'Royal Jordanian', 'JO');
INSERT INTO airlines (id, name, country) VALUES ('RL', 'Royal Khmer Airlines', 'KH');
INSERT INTO airlines (id, name, country) VALUES ('RO', 'Royal Phnom Penh Airways', 'KH');
INSERT INTO airlines (id, name, country) VALUES ('RP', 'Tarom', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('RQ', 'Chautauqua Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('RR', 'Kam Air', 'AF');
INSERT INTO airlines (id, name, country) VALUES ('RS', 'Royal Air Force', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('RU', 'Royal Air Force of Oman', 'OM');
INSERT INTO airlines (id, name, country) VALUES ('RV', 'SkyKing Turks and Caicos Airways', 'TC');
INSERT INTO airlines (id, name, country) VALUES ('RW', 'Caspian Airlines', 'IR');
INSERT INTO airlines (id, name, country) VALUES ('RX', 'Republic Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('RZ', 'Aviaexpress', 'HU');
INSERT INTO airlines (id, name, country) VALUES ('S0', 'Euro Exec Express', 'SE');
INSERT INTO airlines (id, name, country) VALUES ('S2', 'Slok Air Gambia', 'GM');
INSERT INTO airlines (id, name, country) VALUES ('S3', 'Air Sahara', 'IN');
INSERT INTO airlines (id, name, country) VALUES ('S4', 'Santa Barbara Airlines', 'VE');
INSERT INTO airlines (id, name, country) VALUES ('S5', 'SATA International', 'PT');
INSERT INTO airlines (id, name, country) VALUES ('S6', 'Trast Aero', 'KG');
INSERT INTO airlines (id, name, country) VALUES ('S7', 'Star Air', 'DK');
INSERT INTO airlines (id, name, country) VALUES ('S8', 'S7 Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('S9', 'Shovkoviy Shlyah', 'UA');
INSERT INTO airlines (id, name, country) VALUES ('SA', 'East African Safari Air', 'KE');
INSERT INTO airlines (id, name, country) VALUES ('SB', 'South African Airways', 'ZA');
INSERT INTO airlines (id, name, country) VALUES ('SC', 'Air Caledonie International', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('SD', 'Shandong Airlines', 'CN');
INSERT INTO airlines (id, name, country) VALUES ('SE', 'Sudan Airways', 'SD');
INSERT INTO airlines (id, name, country) VALUES ('SF', 'XL Airways France', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('SG', 'Tassili Airlines', 'DZ');
INSERT INTO airlines (id, name, country) VALUES ('SH', 'Spicejet', 'IN');
INSERT INTO airlines (id, name, country) VALUES ('SI', 'Fly Me Sweden', 'SE');
INSERT INTO airlines (id, name, country) VALUES ('SJ', 'Skynet Airlines', 'IE');
INSERT INTO airlines (id, name, country) VALUES ('SK', 'Freedom Air', 'NC');
INSERT INTO airlines (id, name, country) VALUES ('SL', 'SAS Braathens', 'NO');
INSERT INTO airlines (id, name, country) VALUES ('SM', 'Rio Sul Serviços Aéreos Regionais', 'BR');
INSERT INTO airlines (id, name, country) VALUES ('SN', 'Swedline Express', 'SE');
INSERT INTO airlines (id, name, country) VALUES ('SO', 'Brussels Airlines', 'BE');
INSERT INTO airlines (id, name, country) VALUES ('SP', 'Sosoliso Airlines', 'NG');
INSERT INTO airlines (id, name, country) VALUES ('SQ', 'SATA Air Acores', 'PT');
INSERT INTO airlines (id, name, country) VALUES ('SR', 'Singapore Airlines Cargo', 'SG');
INSERT INTO airlines (id, name, country) VALUES ('SS', 'Swissair', 'CH');
INSERT INTO airlines (id, name, country) VALUES ('ST', 'Corsairfly', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('SU', 'Germania', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('SV', 'Aeroflot Russian Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('SW', 'Saudi Arabian Airlines', 'SA');
INSERT INTO airlines (id, name, country) VALUES ('SX', 'Air Namibia', 'NA');
INSERT INTO airlines (id, name, country) VALUES ('SY', 'Skybus Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('T2', 'Sun Country Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('T3', 'Thai Air Cargo', 'TH');
INSERT INTO airlines (id, name, country) VALUES ('T4', 'Eastern Airways', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('T6', 'Hellas Jet', 'GR');
INSERT INTO airlines (id, name, country) VALUES ('T7', 'Tavrey Airlines', 'UA');
INSERT INTO airlines (id, name, country) VALUES ('T9', 'Twin Jet', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('TC', 'Thai Star Airlines', 'TH');
INSERT INTO airlines (id, name, country) VALUES ('TD', 'Air Tanzania', 'TZ');
INSERT INTO airlines (id, name, country) VALUES ('TE', 'Tulip Air', 'NP');
INSERT INTO airlines (id, name, country) VALUES ('TF', 'FlyLal', 'LT');
INSERT INTO airlines (id, name, country) VALUES ('TG', 'MalmÃ¶ Aviation', 'SE');
INSERT INTO airlines (id, name, country) VALUES ('TH', 'Thai Airways International', 'TH');
INSERT INTO airlines (id, name, country) VALUES ('TI', 'Transmile Air Services', 'MY');
INSERT INTO airlines (id, name, country) VALUES ('TK', 'Tol-Air Services', 'US');
INSERT INTO airlines (id, name, country) VALUES ('TL', 'Turkish Airlines', 'TR');
INSERT INTO airlines (id, name, country) VALUES ('TN', 'Trans Mediterranean Airlines', 'LB');
INSERT INTO airlines (id, name, country) VALUES ('TO', 'Air Tahiti Nui', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('TP', 'President Airlines', 'KH');
INSERT INTO airlines (id, name, country) VALUES ('TQ', 'TAP Portugal', 'PT');
INSERT INTO airlines (id, name, country) VALUES ('TR', 'Tandem Aero', 'MD');
INSERT INTO airlines (id, name, country) VALUES ('TS', 'Tiger Airways', 'SG');
INSERT INTO airlines (id, name, country) VALUES ('TT', 'Air Transat', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('TU', 'Tiger Airways Australia', 'AU');
INSERT INTO airlines (id, name, country) VALUES ('TV', 'Tunisair', 'TN');
INSERT INTO airlines (id, name, country) VALUES ('TW', 'Virgin Express', 'BE');
INSERT INTO airlines (id, name, country) VALUES ('TX', 'Trans World Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('TY', 'Air Caraïbes', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('TZ', 'Iberworld', 'ES');
INSERT INTO airlines (id, name, country) VALUES ('U2', 'ATA Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('U3', 'United Feeder Service', 'US');
INSERT INTO airlines (id, name, country) VALUES ('U4', 'Avies', 'EE');
INSERT INTO airlines (id, name, country) VALUES ('U5', 'PMTair', 'KH');
INSERT INTO airlines (id, name, country) VALUES ('U6', 'USA3000 Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('U7', 'Ural Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('U8', 'USA Jet Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('UA', 'Armavia', 'AM');
INSERT INTO airlines (id, name, country) VALUES ('UB', 'United Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('UD', 'Myanma Airways', 'MM');
INSERT INTO airlines (id, name, country) VALUES ('UE', 'Hex''Air', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('UF', 'Transeuropean Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('UG', 'UM Airlines', 'UA');
INSERT INTO airlines (id, name, country) VALUES ('UH', 'Tuninter', 'TN');
INSERT INTO airlines (id, name, country) VALUES ('UI', 'US Helicopter Corporation', 'US');
INSERT INTO airlines (id, name, country) VALUES ('UL', 'Eurocypria Airlines', 'CY');
INSERT INTO airlines (id, name, country) VALUES ('UM', 'SriLankan Airlines', 'LK');
INSERT INTO airlines (id, name, country) VALUES ('UN', 'Air Zimbabwe', 'ZW');
INSERT INTO airlines (id, name, country) VALUES ('UO', 'Transaero Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('UP', 'Hong Kong Express Airways', 'HK');
INSERT INTO airlines (id, name, country) VALUES ('UQ', 'Bahamasair', 'BS');
INSERT INTO airlines (id, name, country) VALUES ('US', 'O''Connor Airlines', 'AU');
INSERT INTO airlines (id, name, country) VALUES ('UT', 'USAir Express', 'US');
INSERT INTO airlines (id, name, country) VALUES ('UU', 'UTair Aviation', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('UX', 'Air Austral', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('UY', 'Air Europa', 'ES');
INSERT INTO airlines (id, name, country) VALUES ('UZ', 'Cameroon Airlines', 'CM');
INSERT INTO airlines (id, name, country) VALUES ('V0', 'El-Buraq Air Transport', 'LY');
INSERT INTO airlines (id, name, country) VALUES ('V2', 'Conviasa', 'VE');
INSERT INTO airlines (id, name, country) VALUES ('V3', 'Karat', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('V4', 'Carpatair', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('V5', 'Reem Air', 'KG');
INSERT INTO airlines (id, name, country) VALUES ('V7', 'Royal Aruban Airline', 'AW');
INSERT INTO airlines (id, name, country) VALUES ('V8', 'Air Senegal International', 'SN');
INSERT INTO airlines (id, name, country) VALUES ('V9', 'ATRAN Cargo Airlines', 'RU');
INSERT INTO airlines (id, name, country) VALUES ('VA', 'BAL Bashkirian Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('VC', 'Viasa', 'VE');
INSERT INTO airlines (id, name, country) VALUES ('VD', 'Voyageur Airways', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('VE', 'SwedJet Airways', 'SE');
INSERT INTO airlines (id, name, country) VALUES ('VF', 'Volare Airlines', 'IT');
INSERT INTO airlines (id, name, country) VALUES ('VG', 'Valuair', 'SG');
INSERT INTO airlines (id, name, country) VALUES ('VI', 'VLM Airlines', 'BE');
INSERT INTO airlines (id, name, country) VALUES ('VJ', 'Volga-Dnepr Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('VK', 'Jatayu Airlines', 'ID');
INSERT INTO airlines (id, name, country) VALUES ('VL', 'Virgin Nigeria Airways', 'NG');
INSERT INTO airlines (id, name, country) VALUES ('VM', 'Air VIA', 'BG');
INSERT INTO airlines (id, name, country) VALUES ('VN', 'Viaggio Air', 'BG');
INSERT INTO airlines (id, name, country) VALUES ('VO', 'Vietnam Airlines', 'VN');
INSERT INTO airlines (id, name, country) VALUES ('VP', 'Austrian Arrows', 'AT');
INSERT INTO airlines (id, name, country) VALUES ('VR', 'VASP', 'BR');
INSERT INTO airlines (id, name, country) VALUES ('VS', 'TACV', 'PT');
INSERT INTO airlines (id, name, country) VALUES ('VT', 'Virgin Atlantic Airways', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('VU', 'Air Tahiti', 'PF');
INSERT INTO airlines (id, name, country) VALUES ('VV', 'Air Ivoire', 'IT');
INSERT INTO airlines (id, name, country) VALUES ('VW', 'Aerosvit Airlines', 'UA');
INSERT INTO airlines (id, name, country) VALUES ('VX', 'Aeromar', 'MX');
INSERT INTO airlines (id, name, country) VALUES ('VY', 'Virgin America', 'US');
INSERT INTO airlines (id, name, country) VALUES ('VZ', 'Vueling Airlines', 'ES');
INSERT INTO airlines (id, name, country) VALUES ('W1', 'MyTravel Airways', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('W2', 'WDL Aviation', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('W3', 'Canadian Western Airlines', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('W4', 'Flyhy Cargo Airlines', 'TH');
INSERT INTO airlines (id, name, country) VALUES ('W5', 'Aero Services Executive', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('W6', 'Mahan Air', 'IR');
INSERT INTO airlines (id, name, country) VALUES ('W8', 'Wizz Air', 'BG');
INSERT INTO airlines (id, name, country) VALUES ('W9', 'Cargojet Airways', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('WA', 'Eastwind Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('WB', 'Western Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('WC', 'Rwandair Express', 'RW');
INSERT INTO airlines (id, name, country) VALUES ('WD', 'Islena De Inversiones', 'HN');
INSERT INTO airlines (id, name, country) VALUES ('WE', 'DAS Air Cargo', 'UG');
INSERT INTO airlines (id, name, country) VALUES ('WF', 'Centurion Air Cargo', 'US');
INSERT INTO airlines (id, name, country) VALUES ('WG', 'Widerøe', 'NO');
INSERT INTO airlines (id, name, country) VALUES ('WH', 'Sunwing Airlines', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('WJ', 'China Northwest Airlines', 'CN');
INSERT INTO airlines (id, name, country) VALUES ('WK', 'WebJet Linhas Aéreas', 'BR');
INSERT INTO airlines (id, name, country) VALUES ('WN', 'Edelweiss Air', 'CH');
INSERT INTO airlines (id, name, country) VALUES ('WO', 'Southwest Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('WR', 'World Airways', 'US');
INSERT INTO airlines (id, name, country) VALUES ('WS', 'Royal Tongan Airlines', 'TO');
INSERT INTO airlines (id, name, country) VALUES ('WT', 'WestJet', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('WV', 'Wasaya Airways', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('WW', 'Swe Fly', 'SE');
INSERT INTO airlines (id, name, country) VALUES ('WX', 'Bmibaby', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('WY', 'CityJet', 'IE');
INSERT INTO airlines (id, name, country) VALUES ('WZ', 'Oman Air', 'OM');
INSERT INTO airlines (id, name, country) VALUES ('X3', 'West African Airlines', 'BJ');
INSERT INTO airlines (id, name, country) VALUES ('X7', 'Hapag-Lloyd Express (TUIfly)', 'DE');
INSERT INTO airlines (id, name, country) VALUES ('XE', 'Chitaavia', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('XF', 'ExpressJet', 'US');
INSERT INTO airlines (id, name, country) VALUES ('XG', 'Vladivostok Air', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('XJ', 'Calima Aviacion', 'ES');
INSERT INTO airlines (id, name, country) VALUES ('XK', 'Mesaba Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('XL', 'Corse-Mediterranee', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('XM', 'Aerolane', 'EC');
INSERT INTO airlines (id, name, country) VALUES ('XO', 'J-Air', 'JP');
INSERT INTO airlines (id, name, country) VALUES ('XP', 'LTE International Airways', 'ES');
INSERT INTO airlines (id, name, country) VALUES ('XQ', 'Xtra Airways', 'US');
INSERT INTO airlines (id, name, country) VALUES ('XS', 'SunExpress', 'TR');
INSERT INTO airlines (id, name, country) VALUES ('XT', 'SITA', 'BE');
INSERT INTO airlines (id, name, country) VALUES ('Y4', 'SkyStar Airways', 'TH');
INSERT INTO airlines (id, name, country) VALUES ('Y5', 'Volaris', 'MX');
INSERT INTO airlines (id, name, country) VALUES ('Y8', 'Pace Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('Y9', 'Yangtze River Express', 'CN');
INSERT INTO airlines (id, name, country) VALUES ('YH', 'Kish Air', 'IR');
INSERT INTO airlines (id, name, country) VALUES ('YK', 'West Caribbean Airways', 'CO');
INSERT INTO airlines (id, name, country) VALUES ('YL', 'Cyprus Turkish Airlines', 'TR');
INSERT INTO airlines (id, name, country) VALUES ('YM', 'Yamal Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('YS', 'Montenegro Airlines', 'ME');
INSERT INTO airlines (id, name, country) VALUES ('YT', 'Régional Compagnie Aérienne Européenne', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('YV', 'Air Togo', 'TG');
INSERT INTO airlines (id, name, country) VALUES ('YW', 'Mesa Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('YX', 'Air Nostrum', 'ES');
INSERT INTO airlines (id, name, country) VALUES ('Z3', 'Midwest Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('Z4', 'Avient Aviation', 'ZW');
INSERT INTO airlines (id, name, country) VALUES ('Z7', 'Zoom Airlines', 'CA');
INSERT INTO airlines (id, name, country) VALUES ('Z8', 'ADC Airlines', 'NG');
INSERT INTO airlines (id, name, country) VALUES ('ZA', 'Amaszonas', 'BO');
INSERT INTO airlines (id, name, country) VALUES ('ZB', 'Interavia Airlines', 'RO');
INSERT INTO airlines (id, name, country) VALUES ('ZE', 'Monarch Airlines', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('ZG', 'Lineas Aereas Azteca', 'MX');
INSERT INTO airlines (id, name, country) VALUES ('ZH', 'Viva Macau', 'LU');
INSERT INTO airlines (id, name, country) VALUES ('ZI', 'Shenzhen Airlines', 'CN');
INSERT INTO airlines (id, name, country) VALUES ('ZK', 'Aigle Azur', 'FR');
INSERT INTO airlines (id, name, country) VALUES ('ZL', 'Great Lakes Airlines', 'US');
INSERT INTO airlines (id, name, country) VALUES ('ZP', 'Regional Express', 'AU');
INSERT INTO airlines (id, name, country) VALUES ('ZS', 'Silk Way Airlines', 'AZ');
INSERT INTO airlines (id, name, country) VALUES ('ZT', 'Sama Airlines', 'SA');
INSERT INTO airlines (id, name, country) VALUES ('ZU', 'Titan Airways', 'GB');
INSERT INTO airlines (id, name, country) VALUES ('ZV', 'Helios Airways', 'CY');
INSERT INTO airlines (id, name, country) VALUES ('ZW', 'Air Midwest', 'US');
INSERT INTO airlines (id, name, country) VALUES ('ZX', 'Air Wisconsin', 'US');
INSERT INTO airlines (id, name, country) VALUES ('ZY', 'Air Georgian', 'CA');
